---
title: "Citi_proj"
author: "Patrick Lucey"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
library(duckdb)
library(DBI)
library(dplyr)
library(dbplyr)
library(ggplot2)
library(arrow)
library(prettymapr)
library(sf)
library(ggspatial)
```

```{r}
con <- DBI::dbConnect(duckdb::duckdb(), ":memory:")

```

```{sql, connection=con} 
create or replace view citi as select * EXCLUDE(started_at, starttime, stoptime, ended_at,start_station_latitude,start_station_longitude, start_lat, start_lng, end_lat,end_lng, end_station_latitude, end_station_longitude, tripduration),
  coalesce(started_at, starttime) as starttime,
  coalesce(ended_at, stoptime) as stoptime,
  coalesce(start_station_latitude, start_lat) as start_lat,
  coalesce(start_station_longitude, start_lng) as start_long,
  coalesce(end_station_latitude, end_lat) as end_lat,
  coalesce(end_station_longitude, end_lng) as end_long,
  round(coalesce(tripduration, date_diff('seconds', coalesce(started_at, starttime), coalesce(ended_at, stoptime)))/ 60)  as tripduration_min,
  ROUND(
        3959 * 2 * ASIN(SQRT(
            POWER(SIN(RADIANS(coalesce(end_station_latitude, end_lat) - coalesce(start_station_latitude, start_lat)) / 2), 2) +
            COS(RADIANS(coalesce(start_station_latitude, start_lat))) * COS(RADIANS(coalesce(end_station_latitude, end_lat))) * 
            POWER(SIN(RADIANS( coalesce(end_station_longitude, end_lng) - coalesce(start_station_longitude, start_lng)) / 2), 2)
        )), 2
    ) AS distance_between_start_end_station_km
  FROM read_parquet('trip_data/trip_year=*/trip_month=*/*.parquet', union_by_name=1);
```

```{sql, connection=con, output.var='citi_sum'}
summarize citi
```

```{sql, connection=con}
select columns('(duration|time)') from citi limit 10
```

```{sql, connection=con}
summarize SELECT 
    start_lat,
    start_long,
    end_lat,
    end_long,
    ROUND(
        3959 * 2 * ASIN(SQRT(
            POWER(SIN(RADIANS(end_lat - start_lat) / 2), 2) +
            COS(RADIANS(start_lat)) * COS(RADIANS(end_lat)) * 
            POWER(SIN(RADIANS(end_long - start_long) / 2), 2)
        )), 2
    ) AS distance_between_start_end_station
FROM citi;

```

```{sql, connection=con}
SELECT 
    HOUR(starttime) AS hour_of_day,
    AVG(distance_between_start_end_station_km) AS avg_distance
FROM 
    citi
GROUP BY 
    hour_of_day
ORDER BY 
    hour_of_day;
```
```{sql, connection=con}
select count(*)
from citi 
where start_station_name = 'Central Park S & 6 Ave' and end_station_name = 'Central Park S & 6 Ave'
; 

```

```{sql, connection=con}
SELECT 
start_station_name, end_station_name, 
    AVG(tripduration_min) AS avg_trip_duration,
    count(*) as num_trips, 
    distance_between_start_end_station_km
FROM 
    citi
GROUP BY 
    all
ORDER BY 
    num_trips desc limit 100;
```

```{r}
num_trips <- DBI::dbGetQuery(con, 'SELECT 
start_station_name, end_station_name, 
    AVG(tripduration_min) AS avg_trip_duration,
    count(*) as num_trips
FROM 
    citi
GROUP BY 
    all
ORDER BY 
    num_trips desc limit 100;')

```



```{sql, connection=con, eval = FALSE}
select 
 round(coalesce(tripduration, tripduration1) / 60) as tripduration_min
  
from citi
where trip_year = 2020;
```



```{sql, connection=con}
SELECT 
    AVG(tripduration) / 60 AS average_trip_minutes
FROM 
    citi
GROUP BY 
    trip_year
ORDER BY 
    trip_year;
```



```{sql, connection=con, output.var = numtrips}
SELECT 
    station_name,
    COUNT(*) AS num_trips
FROM (
    SELECT 
        start_station_name AS station_name
    FROM 
    citi
    WHERE 
        start_station_name IS NOT NULL AND start_station_name <> ''
    
    UNION ALL
    
    SELECT 
        end_station_name AS station_name
    FROM 
        citi
    WHERE 
        end_station_name IS NOT NULL AND end_station_name <> ''
) AS combined_stations
GROUP BY 
    station_name
ORDER BY 
    num_trips DESC
LIMIT 
    10;

```

```{sql, connection=con}
SELECT 
    station_name,
    COUNT(*) AS num_trips
FROM (
    SELECT 
        start_station_name AS station_name
    FROM 
    citi
    WHERE 
        start_station_name IS NOT NULL AND start_station_name <> ''
    
    UNION ALL
    
    SELECT 
        end_station_name AS station_name
    FROM 
        citi
    WHERE 
        end_station_name IS NOT NULL AND end_station_name <> ''
) AS combined_stations
GROUP BY 
    station_name
ORDER BY 
    num_trips ASC
LIMIT 
    10;

```



```{r, eval=FALSE}
ggplot(numtrips, aes(x = reorder(station_name, -num_trips), y = num_trips)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +  # Flip coordinates for better readability
  labs(title = "Top 10 Citibike Stations by Number of Trips",
       x = "Station Name",
       y = "Number of Trips") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{sql, connection=con}
WITH trip_counts AS (
    SELECT 
        start_station_id AS station_id,
        COUNT(*) AS num_trips
    FROM 
        citi
    WHERE 
        start_station_id IS NOT NULL
    GROUP BY 
        start_station_id
    
    UNION ALL
    
    SELECT 
        end_station_id AS station_id,
        COUNT(*) AS num_trips
    FROM 
       citi
    WHERE 
        end_station_id IS NOT NULL
    GROUP BY 
        end_station_id
)

SELECT 
    station_id,
    SUM(num_trips) AS total_trips
FROM 
    trip_counts
GROUP BY 
    station_id
```

```{sql, connection=con, output.var=heat}
SELECT 
    station_name,
    latitude,
    longitude,
    Month(trip_date) AS month,
    COUNT(*) AS num_trips
FROM (
    SELECT 
        start_station_name AS station_name,
        start_station_latitude AS latitude,
        start_station_longitude AS longitude,
        starttime AS trip_date
    FROM 
       citi
    WHERE 
        start_station_name IS NOT NULL AND start_station_name <> ''
        AND start_station_latitude IS NOT NULL AND start_station_longitude IS NOT NULL
    
    UNION ALL
    
    SELECT 
        end_station_name AS station_name,
        end_station_latitude AS latitude,
        end_station_longitude AS longitude,
        stoptime AS trip_date
    FROM 
        citi
    WHERE 
        end_station_name IS NOT NULL AND end_station_name <> ''
        AND end_station_latitude IS NOT NULL AND end_station_longitude IS NOT NULL
) AS combined_stations
GROUP BY all
    
ORDER BY 
    num_trips DESC;
```


```{sql, connection=con, output.var=heat2022, eval=FALSE}
SELECT 
    station_name,
    latitude,
    longitude,
    DATE_TRUNC('month', trip_date) AS month,
    COUNT(*) AS num_trips
FROM (
    SELECT 
        start_station_name AS station_name,
        start_lat AS latitude,
        start_lng AS longitude,
        started_at AS trip_date
    FROM 
       citi
    WHERE 
        start_station_name IS NOT NULL AND start_station_name <> ''
        AND start_station_latitude IS NOT NULL AND start_station_longitude IS NOT NULL
    
    UNION ALL
    
    SELECT 
        end_station_name AS station_name,
        end_lat AS latitude,
        end_lng AS longitude,
        ended_at AS trip_date
    FROM 
        citi
    WHERE 
        end_station_name IS NOT NULL AND end_station_name <> ''
        AND end_station_latitude IS NOT NULL AND end_station_longitude IS NOT NULL
) AS combined_stations
GROUP BY 
    station_name, latitude, longitude, DATE_TRUNC('month', trip_date)
ORDER BY 
    num_trips DESC;

```



```{r}
result_sf <- st_as_sf(heat, coords = c("longitude", "latitude"), crs = 4326)
```

```{r}
nyc_bbox <- st_bbox(c(xmin = -74.05, ymin = 40.68, xmax = -73.85, ymax = 40.85), crs = st_crs(4326))
nyc_map <- ggplot() +
  annotation_map_tile(type = "cartolight", zoom = 12)
```


```{r}
# Create the geographical map
nyc_map +
  geom_sf(data = result_sf, aes(color = num_trips), alpha = 0.7) +
  scale_color_gradient(low = "blue", high = "red") +
  labs(title = "Geographical Map of Citi Bike Station Usage",
       x = "Longitude",
       y = "Latitude",
       size = "Number of Trips",
       color = "Number of Trips") +
  theme_light() +
  theme(legend.position = "right") + facet_wrap(~ month, ncol = 3)
```

```{r}
citi <- tbl(con, "citi")
```

```{r}
show(citi)
```

```{r}
citi %>%
  group_by(trip_year) %>%
  summarize(total = n()) %>%
  arrange(trip_year) %>%
  show_query()
```

```{r}
DBI::dbDisconnect(conn = con, shutdown = TRUE)
```
